
security_tests:
  image: ubuntu
  script:
    - apt-get -y update; apt-get -y install curl; apt-get install -yqq jq
    - export VERACODE_API_KEY_ID=$VERACODE_ID
    - export VERACODE_API_KEY_SECRET=$VERACODE_KEY
    - curl -fsS https://tools.veracode.com/veracode-cli/install | sh
    - ./veracode scan --type directory --source ${CI_PROJECT_DIR} --output veracode_terragoat.json
    - export PASSFAIL=$(jq -r .policy-passed veracode_terragoat.json)
    - sys.exit(PASSFAIL)
  artifacts:
    paths:
      - veracode_terragoat.json
    expire_in: 1 week