trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Veracode Container Scan'
  
  inputs:
    targetType: inline
    script: |
      export VERACODE_API_KEY_ID=$(VERACODE_API_KEY_ID)
      export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY_SECRET)
      curl -fsS https://tools.veracode.com/veracode-cli/install | sh > ./install.log 2>&1
      echo Scan repo
      ./veracode scan --source https://github.com/christyson/terragoatfork --type repo --output $(System.DefaultWorkingDirectory)/veracode_terragoat.json

- publish: $(System.DefaultWorkingDirectory)/veracode_terragoat.json
  artifact: pipeline
  displayName: 'Publish the baseline file'

- task: Bash@3
  displayName: 'Check for error'
  inputs:
    targetType: inline
    script: |
      export PASSFAIL=$(jq -r '."policy-passed"' ./veracode_terragoat.json)
      echo Policy passed = $PASSFAIL
      if [ $PASSFAIL == "false" ]; then exit 1; fi