name: Veeracode Container IaC Secrets Scan
on:
  push:
    branches:
      - master

Veracode-container_iac_secrets-scan:
    runs-on: ubuntu-latest
    name: Verracode Container/IaC/Secrets scan

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Verracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.0
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          command: "scan" 
          type: "directory"
          source: "./"
          format: "json"
          debug: false
          fail_build: true
